# I used a build environment built from this Dockerfile to build
# netty-3.10.6-lendup on my workstation for local testing/development

FROM openjdk:8

RUN apt-get -y update

RUN apt-get -y install maven

